language: c++
install:
  - sudo apt-get update -qq
  - sudo apt-get install g++ cmake libboost-all-dev pandoc zlib1g-dev libbz2-dev libsqlite3-dev
script:
  - mkdir build && cd build && cmake .. && make && make test
